test_that("works", {
  message('System PATH')
  message(Sys.getenv('PATH'))
  message('blast path')
  path <- blast_plus_path()
  message(path)
  message('n files')
  files <- list.files(path)
  message('n files: ', length(files))
  expect_length(path, 1)
})
