test_that("works", {
  message('System PATH')
  message(Sys.getenv('PATH'))
  message('blast path')
  path <- blast_plus_path()
  message(path)
  message('n files')
  files <- list.files('/opt/hostedtoolcache/blast/', recursive = TRUE)
  print(files)
  expect_length(path, 1)
})
